steps:
  - name: maven:3.6.3-jdk-11
    entrypoint: mvn
    args: ['install']
    dir: 'payment-service/'
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west4-docker.pkg.dev/project-us-350-08/docker-repository/payment-service:1.3.0", "."]
    dir: 'payment-service/'
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west4-docker.pkg.dev/project-us-350-08/docker-repository/payment-service:1.3.0"]
    dir: 'payment-service/'
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: 'payment-service/'
    args:
      - run
      - --filename=gke
      - --location=europe-west4-a
      - --cluster=${_GKE_CLUSTER}
  substitutions:
    _LOCATION: europe-west4-a
    _GKE_CLUSTER: gke-workshop